Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network", ip: "192.168.56.24", netmask: "255.255.255.0"
  config.disksize.size = "50GB"
  # provider config
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2056"
    vb.name = "repo-server"
    vb.cpus = 1
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../setup.yml"

  end
end
